version: '3.9'
services:
  opengl-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: opengl-node
    volumes:
       - .:/usr/src/opengl-node
    command: [node, index.js]